import numpy as np

BUG_SHAPE = np.array([
    [np.nan, np.nan, np.nan, np.nan, 2, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 2, np.nan, np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, 1, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 1, np.nan, np.nan, np.nan, np.nan],
    [np.nan, 2, np.nan, np.nan, 1, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 1, np.nan, np.nan, 2, np.nan],
    [np.nan, 1, np.nan, np.nan, 1, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 1, np.nan, np.nan, 1, np.nan],
    [np.nan, 1, np.nan, np.nan, 1, np.nan, 1, 1, 1, 1, np.nan, 1, np.nan,
     np.nan, 1, np.nan],
    [np.nan, 1, 1, np.nan, np.nan, 1, 1, 1, 1, 1, 1, np.nan, np.nan, 1, 1,
     np.nan],
    [np.nan, np.nan, 1, 1, np.nan, 1, 2, 1, 1, 2, 1, np.nan, 1, 1, np.nan,
     np.nan],
    [np.nan, np.nan, np.nan, np.nan, 1, 1, 2, 1, 1, 2, 1, 1, np.nan, np.nan,
     np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, np.nan, 1, 2, 1, 1, 2, 1, np.nan, np.nan,
     np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, np.nan, np.nan,
     np.nan],
    [np.nan, 1, 1, np.nan, np.nan, 1, 2, 1, 1, 2, 1, np.nan, np.nan, 1, 1,
     np.nan],
    [np.nan, 1, np.nan, np.nan, 1, 1, 1, 1, 1, 1, 1, 1, np.nan, np.nan, 1,
     np.nan],
    [np.nan, 1, np.nan, np.nan, 1, np.nan, 1, 1, 1, 1, np.nan, 1, np.nan,
     np.nan, 1, np.nan],
    [np.nan, 2, np.nan, np.nan, 1, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 1, np.nan, np.nan, 2, np.nan],
    [np.nan, np.nan, np.nan, np.nan, 1, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 1, np.nan, np.nan, np.nan, np.nan],
    [np.nan, np.nan, np.nan, np.nan, 2, np.nan, np.nan, np.nan, np.nan, np.nan,
     np.nan, 2, np.nan, np.nan, np.nan, np.nan],
], dtype=float)
