name: generate contribution SVGs

on:
  schedule:
    - cron: "0 0 * * *"  # each 24 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate lizard
        uses: carlosbravo1408/Lizard@v1
        with:
          user_name: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/contribution_map_animation_light.svg
            dist/contribution_map_animation_dark.svg

      - name: Commit and push SVG
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}