name: generate contribution SVGs

on:
  schedule:
    - cron: "0 0 * * *"  # cada 24 horas a medianoche
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Generate SVGs for light and dark themes
      - name: Generate contribution SVGs
        run: |
          mkdir -p dist
          python main.py --user_name "${{ github.repository_owner }}" --token "${{ secrets.GITHUB_TOKEN }}"

      # Push the generated SVGs to output branch
      - name: Publish SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}